// <auto-generated />
using System;
using BoschBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoschBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20200325214123_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BoschBot.Models.UserScore", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CurrentDailyStreak")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDailyClaimed")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.ToTable("UserScores");
                });
#pragma warning restore 612, 618
        }
    }
}
